"""empty message

Revision ID: 5cc79033c056
Revises: 
Create Date: 2024-03-22 19:32:04.279361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5cc79033c056'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_time', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('join_time')

    op.drop_table('student')
    # ### end Alembic commands ###
